apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-basic-pvc
  labels:
    app: minio-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi